<!-- SYNTAX TO DROP DATABASE -->
DROP DATABASE DATABASENAME;

<!-- EXAMPLE TO DROP DATABASE -->
DROP DATABASE testDB;

<!-- SYNTAX TO DROP TABLE -->
DROP TABLE TABLENAME;

<!-- EXAMPLE TO DROP TABLE -->
DROP TABLE Person;

<!-- SYNTAX TO DELETE EACH DATA OF TABLE -->
TRUNCATE TABLE TABLENAME;

<!-- EXAMPLE TO DELETE EACH DATA OF TABLE -->
TRUNCATE TABLE PERSON;

<!-- SYNTAX TO DELETE TABLE DATA -->
DELETE FROM TABLENAME WHERE columnname1='Value1';

<!-- EXAMPLE -->
DELETE FROM Persons WHERE PersonID='1';