<!-- SYNTAX -->
SELECT * FROM TABLENAME;

<!-- EXAMPLE TO SELECT WHOLE TABLE-->
SELECT * FROM Person;

<!-- EXAMPLE TO SELECT SPECIFY COLUMN -->
SELECT FirstName, City FROM Person;

<!-- SYNTAX TO SELECT 2 TABLE WITH INNER JOIN -->
SELECT TABLE1.COLUMN, TABLE2.COLUMN
FROM TABLE1
INNER JOIN TABLE2 ON TABLE1.COLUMN = TABLE2.COLUMN;

<!-- EXAMPLE TO SELECT 2 TABLE WITH INNER JOIN -->
SELECT Orders.OrderID, Customers.CustomerName
FROM Orders
INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID;